### ISSUE TITLE
Опечатка в readme.md

### ISSUE THREAD

**Issue by shevl-dev** [forest-lynx/moonshine-resource-lock#2]
![Screenshot_20240702_181418_GitHub.jpg](https://github.com/forest-lynx/moonshine-resource-lock/assets/118539450/23f094b9-abf1-4e24-b3a1-f8b014050ca0)

Предоставляет возможность )

**Comment by forest-lynx** [comment]
Добрый день! Огромное спасибо выявленные недостатки в пакете.
